# Generated by Django 4.2.17 on 2024-12-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('full_path', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('filename', 'full_path'), include=('id', 'created_date'), name='doc_filenamepath_non_identical'),
        ),
    ]
